### ISSUE TITLE
I can not install the vim plugin manually

### ISSUE THREAD

**Issue by fatjyc** [kiteco/plugins#100]
I type 

```
git clone https://github.com/kiteco/vim-plugin.git ~/.config/nvim/pack/kite/start/kite/
```

the result is , wait to type username.

and i can not find https://github.com/kiteco/vim-plugin this repo.

**Comment by jansorg** [comment]
@fatjyc Thanks for reporting this! You're right, the repository isn't public at this time. We'll look into this.

Is the plugin manager not detecting your installation of VIM or are there other reasons why you'd like to install manually?

**Comment by adamsmith** [comment]
@jansorg note I removed references to manual installation in the vim page.

https://github.com/kiteco/plugins/commit/8776275a38f1fbcf3f242dec322a50471613195c
