### ISSUE TITLE
[Feature request] Sublime Text plugin source

### ISSUE THREAD

**Issue by Kristinita** [kiteco/plugins#101]
### 1. Summary

It would be nice, if you add source of Sublime Text Kite plugin to any hosting as GitLab, BitBucket or GitHub.

### 2. Argumentation

1. For example, I want to create a pull request. But at the time I can't find repository for pull request.
1. It would be nice, if issues for each plugin will in separate repositories. I think it will be more convenient to Kite staff.

Thanks.

**Comment by adamsmith** [comment]
Hi @Kristinita, thank you for the feedback.  While we don't have plans to open source the Sublime Text 3 plugin currently, we will keep this in mind.  In the mean time please feel free to post any issues you run into here and note them as related to ST3.

Thanks again!
