### ISSUE TITLE
IntelliJ PyCharm default value for parameters

### ISSUE THREAD

**Issue by lovegandhi** [kiteco/plugins#104]
Would be nice to see parameter's default value as seen in PyCharm's quick documentation. At a quick glance you can decide if this parameter needs to change from its default behavior.

Pycharm:
<img width="732" alt="screen shot 2018-04-16 at 2 22 20 pm" src="https://user-images.githubusercontent.com/2529411/38883648-977eef7e-423b-11e8-9c7c-17daa8020dc6.png">

Kite:
<img width="821" alt="screen shot 2018-04-16 at 2 23 44 pm" src="https://user-images.githubusercontent.com/2529411/38883661-a033859e-423b-11e8-8893-d9afdb3559f1.png">

**Comment by jansorg** [comment]
@lovegandhi Thank you for reporting this!

The PyCharm plugin should render default values, it doesn't render default types atm. So it should have been "optional=False".

Could you provide the version of the plugin which is installed? 
Our latest version is 1.1.118, as shown in the screenshot.
![screenshot_20180418_183821](https://user-images.githubusercontent.com/11473063/38945744-ac6eaf9e-4337-11e8-9695-2b2d633671b3.png)

**Comment by lovegandhi** [comment]
@jansorg I have 1.1.105 installed. I am not able to find Kite when browsing repositories so would it be safe to assume that Kite app is responsible for PyCharm having the latest version of Kite plugin? PyCharm has never informed me of Kite plugin update.
<img width="1126" alt="screen shot 2018-04-18 at 12 47 35 pm" src="https://user-images.githubusercontent.com/2529411/38946311-0eae7cd8-4307-11e8-9e82-03604dcb45d8.png">

**Comment by lovegandhi** [comment]
@jansorg manually Uninstalling and Installing PyCharm plugin gave me 1.1.118 just as your screenshot. However, I still don't see a difference. Kite app is 0417 update from yesterday.
<img width="601" alt="screen shot 2018-04-18 at 12 57 26 pm" src="https://user-images.githubusercontent.com/2529411/38946712-4e5e797c-4308-11e8-96e4-2800dc735e0a.png">

**Comment by jansorg** [comment]
@lovegandhi Thanks for the update! The rendering of default values was added back in 2017. 
To notify about a plugin update is a good idea, I'll look into this.

The cause may be that Kite isn't parsing the defintion of "GetParameter" properly. 
Is it possible that you show/paste the definition of `GetSignature`, i.e. `def GetParameter(...)`?

Do you see default values for `json.dumps()`?
![screenshot_20180418_190459](https://user-images.githubusercontent.com/11473063/38946979-64c24896-433b-11e8-9086-664d2b7b1d18.png)

**Comment by lovegandhi** [comment]
@jansorg ```def GetParameter(self, parameterName, optional=False, ret=''):```

If I do ```import json``` and ```json.dumps(|)``` I am also able to see the default values.

**Comment by adamsmith** [comment]
Interesting!

I see the same behavior as @lovegandhi when I'm looking at cross-file calls.

file1.py:
```
class Test(object):
    def GetParameter(self, parameterName, optional=False, ret=''):
        pass
```

when I call `Test().GetParameter(|)` from file1.py I see the default param (although `False` is lowercased, which is a different issue).

when I call it from file2.py:

```
import file1
file1.Test().GetParameter(|)
```

I see the signature but there isn't the default value for the second param.

![screen shot 2018-04-18 at 10 35 47 am](https://user-images.githubusercontent.com/87728/38948463-8d43a536-42f4-11e8-9b10-e19bed785c27.png)

For what it's worth I see the same thing in Atom:

![screen shot 2018-04-18 at 10 40 53 am](https://user-images.githubusercontent.com/87728/38948641-fc308f0e-42f4-11e8-94cc-00aae10cca60.png)

**Comment by adamsmith** [comment]
Hi @lovegandhi, we think we fixed this!  Check it out and let us know if it's not resolved on your end!

![screen shot 2018-05-24 at 9 46 39 am](https://user-images.githubusercontent.com/87728/40499700-940f1ea4-5f37-11e8-99e8-1516e01bad85.png)

Thanks for the bug report -- really helpful!
