### ISSUE TITLE
Kite Engine clean unused resources

### ISSUE THREAD

**Issue by lovegandhi** [kiteco/plugins#105]
Hi @adamsmith I didn't see a project related to Kite Engine in github so decided to open it here instead.
After Kite has been running for ~24 hours I am seeing that Kite Engine process is not releasing/cleaning some of its connections properly.

Kite version:
<img width="504" alt="screen shot 2018-06-07 at 2 39 39 pm" src="https://user-images.githubusercontent.com/2529411/41119574-20634d6a-6a61-11e8-974e-515b04b077c6.png">

ports field will slowly go up throughout the day and never go down.
<img width="671" alt="screen shot 2018-06-07 at 2 27 22 pm" src="https://user-images.githubusercontent.com/2529411/41119376-a89049e6-6a60-11e8-9e7c-0ded12afba4c.png">

Open Files and Ports section shows all the connections but not their state. Arrow shows the height of that window and how many connections there are.
<img width="675" alt="screen shot 2018-06-07 at 2 27 43 pm" src="https://user-images.githubusercontent.com/2529411/41119495-ef39109e-6a60-11e8-9ed2-eb80e8efe7c7.png">

More detail on the opened ports and their state:
<img width="719" alt="screen shot 2018-06-07 at 2 28 52 pm" src="https://user-images.githubusercontent.com/2529411/41119553-0e493004-6a61-11e8-9e53-d50315c8067a.png">

**Comment by tarakju** [comment]
Hey @lovegandhi! Thanks for bringing this to our attention! We have a couple of theories around the root cause of this, and are also working to replicate the issue internally. I'll keep this thread updated with our progress, or any questions we may have (if you don't mind). Thanks!

**Comment by jansorg** [comment]
@lovegandhi We've found a bug which caused kited to leak HTTP connection. This has been fixed and is already available with the latest updates. Do you still see the resource leak you've reported with the current version?

**Comment by lovegandhi** [comment]
Thanks @jansorg, I will monitor for a few days and let you know my findings.

**Comment by lovegandhi** [comment]
@jansorg after running for 24 hours it seems that issue has been fixed.
