### ISSUE TITLE
Neovim Completion Errors

### ISSUE THREAD

**Issue by dkao1978** [kiteco/plugins#106]
Kite version: 0.20180614.0

Error detected while processing function kite#completion#complete[42]..kite#client#completions[9]..kite#completion#handler:
line 6
E747: Attempt to decode a blank string

It seems like json_decode is not handling an empty string well. Replacing response.body with "{}" when it is an empty string fixes the problem.

**Comment by dhung09** [comment]
Hi @dkao1978, thanks for reporting this bug (and the potential fix 🙂) and sorry for the inconvenience! We're looking into this.

**Comment by adamsmith** [comment]
This should be fixed in the latest version.  Thanks!
