### ISSUE TITLE
IntelliJ PyCharm plugin crash

### ISSUE THREAD

**Issue by lovegandhi** [kiteco/plugins#107]
I am using Pycharm installed through JetBrains Toolbox:
<img width="371" alt="screen shot 2018-06-28 at 5 51 02 pm" src="https://user-images.githubusercontent.com/2529411/42062600-0a19c466-7afc-11e8-9077-0e5315b7dd60.png">

Current installed Kite plugin version:
<img width="434" alt="screen shot 2018-06-28 at 5 35 33 pm" src="https://user-images.githubusercontent.com/2529411/42062642-2a95926a-7afc-11e8-8bd2-1a79154a8279.png">

I have been receiving this crash report and I have to restart the IDE in order to get kite plugin to work again.
<img width="2039" alt="screen shot 2018-06-28 at 5 33 17 pm" src="https://user-images.githubusercontent.com/2529411/42062715-6c0585de-7afc-11e8-9845-bf04658328be.png">

I am not sure what other information I need to provide that would help you debug this.

**Comment by lovegandhi** [comment]
Contents of ~/Library/Application\ Support/PyCharm2018.1/kite-pycharm/lib 
File system contains: kite-pycharm-1.1.159.jar (not the version shown by PyCharm)

<img width="613" alt="screen shot 2018-06-28 at 5 59 15 pm" src="https://user-images.githubusercontent.com/2529411/42062846-13ff0544-7afd-11e8-8547-c77ee74ede1e.png">

**Comment by jansorg** [comment]
@lovegandhi Thanks you for reporting this!
The file for version 1.1.158 wasn't found, but your listing shows 1.1.159. I think that this is the result of an auto-update of the plugin made by Kite. We'll update the plugin auto-update to only install a new version when IntelliJ / PyCharm isn't running to avoid these errors.
We're sorry for any inconvenience and will let you know when we have a fix for this.

**Comment by jansorg** [comment]
@lovegandhi We've rolled out the fix for this issue. Please let us know if it's not yet working as expected or if you run into other issues.
