### ISSUE TITLE
Vim plugin under Linux

### ISSUE THREAD

**Issue by OviVesa** [kiteco/plugins#110]
Hi !
I'm following the vim plugin setup guide and the repo doesn't seem to exist:
git clone https://github.com/kiteco/vim-plugin.git ~/.vim/pack/kite/start/kite/
remote: Repository not found.
fatal: repository 'https://github.com/kiteco/vim-plugin.git/' not found

Has the support for vim been dropped ?

**Comment by dhung09** [comment]
Vim is still supported, though not on Linux unfortunately. We plan to ship Linux support sometime around the new year.

It seems like the Vim plugin was made private, which is why your attempt resulted in "Repository not found". Thanks for bringing attention to this!

**Comment by pistolario** [comment]
The repository keeps being "non existant" and the Kite Copilot can't find my vim in Windows, so I can't use the product.

**Comment by jansorg** [comment]
@OviVesa Late update on this: the vim-plugin repository is now public at https://github.com/kiteco/vim-plugin.git . Linux support was released yesterday to the public.
Please let us know if there's still something missing or not working for you.
