### ISSUE TITLE
Vim function error for macOS Mojave

### ISSUE THREAD

**Issue by kndo** [kiteco/plugins#112]
I am using macOS Mojave 10.14.1. After following the installation guide, I get the following error when I open vim in the terminal, press "i', and start typing.

`Error detected while processing function kite#completion#autocomplete:
line    2:
E15: Invalid expression: b:kite_skip          | return | endif`

Edit: Also, the autocompletion appears to be very broken. I can't even delete a suggested word with the backspace.

Thanks in advance for the help.

**Comment by jansorg** [comment]
@kndo We're sorry for the issues you're observing.
Which type and version of vim do you use (e.g. "MacVIM version" x o "text based vim version x")?
We're looking into the error you're observing, the information above will help us to do this.

**Comment by jansorg** [comment]
@kndo The error about the invalid expression is fixed for the next update. This should be out by tomorrow at the latest. We'll look into the completions asap, the details about completion options and vim's version will help us doing that.

**Comment by kndo** [comment]
@jansorg Thanks for the reply. In case you still need the info, I'm using text-based Vim version 8.0.1283 (I believe it came pre-installed with macOS; if not, I must've installed it via Homebrew). I get `menu,preview` after entering `:echo &cot`.

**Comment by jansorg** [comment]
@kndo Thank you for the info. We've tested with the same version of vim and are unable to reproduce this. This was tested with the first fix already applied. It's likely that that fix will also fix your 2nd issue. The current release `2.2018.1113.0` should have the fix. Please let us know if you're still seeing issues with the current version.
Thanks!

**Comment by kndo** [comment]
@jansorg Problem solved. You can close the issue. Thanks.

**Comment by jansorg** [comment]
@kndo Thanks for the update!
