### ISSUE TITLE
Escape key doesn't work in Sublime Text3 with Kite enabled

### ISSUE THREAD

**Issue by lucidsushi** [kiteco/plugins#114]
`escape` key stops functioning in sublime when kite is enabled, could not exit menus spawn from (ctrl + shift + p - command pallet) and find/replace menu and so on...

No other packages are active at all.

sublime:   version 3.1.1, build 3176
kite:          version 1.2018.1109.0

**Comment by dhung09** [comment]
Hi @lucidsushi thanks for reporting this issue. We're looking into it.

**Comment by dhung09** [comment]
Hi @lucidsushi this should be fixed as of Kite v0.20181113.0. You may need to uninstall/reinstall the Sublime Text plugin from the Copilot for the fix to take effect.

**Comment by lucidsushi** [comment]
Amazing, thank you so much! Now it feels like home again !
