### ISSUE TITLE
Can kite be used offline?

### ISSUE THREAD

**Issue by zhiyiZeng** [kiteco/plugins#117]
I'm using Kite in Atom. However, it's a bit slow because of Internet speed. Is there any way to use kite offline?

**Comment by its-dhung** [comment]
Hi @zhiyiZeng, Kite should work without an internet connection as long as you've created an account and logged in. Please let us know that's not the case and re-open this issue.

**Comment by zhiyiZeng** [comment]
Great! Thanks!
