### ISSUE TITLE
Add spyder editor as plugin

### ISSUE THREAD

**Issue by arita37** [kiteco/plugins#119]
Here, the details of spyder editor :  

https://github.com/spyder-ide

This is very handy editor.

**Comment by caelan-kite** [comment]
Hi @arita37, Spyder + Kite support was released as part of the Spyder 4 release. [More info here](https://kite.com/blog/product/announcing-kite-for-spyder-4/). 

Looking forward to your feedback once you try it, or if you've already tried it out!
