### ISSUE TITLE
Can't load kite.el into Aquamacs

### ISSUE THREAD

**Issue by rpgoldman** [kiteco/plugins#121]
I use the Aquamacs port of emacs on Mac OS.  I haven't been able to figure out how to load the kite plugin, kite.el.  The emacs folder here on GitHub appears to contain only the README, and when I start up Kite, it doesn't show the emacs plug in as available, presumably because it doesn't recognize Aquamacs.
How do I download `kite.el` so that I can put it in `~/.emacs.d/`?

**Comment by its-dhung** [comment]
Hi @rpgoldman, we unfortunately discontinued support for Emacs due to lack of engineering resources. We'll update this repo to make it clear we no longer have an Emacs plugin. Apologies for the confusion and inconvenience!
