### ISSUE TITLE
Kite Plugin not available in Pycharm

### ISSUE THREAD

**Issue by remi-debette** [kiteco/plugins#123]
Hi,

I just tried to follow the documentation of the Pycharm Plugin and it does not exist in the Plugins Marketplace on Pycharm 2018.3
Therefore it cannot be installed.

Thank you

**Comment by jansorg** [comment]
Hi @remi-debette 
the PyCharm plugin comes with the Kite download. It's not yet available on the public plugin repository.
https://help.kite.com/article/62-managing-editor-plugins might be helpful to set up the PyCharm integration.
