### ISSUE TITLE
Vim plugin permission denied

### ISSUE THREAD

**Issue by BwL1289** [kiteco/plugins#129]
Cannot install the vim plugin through kite. The error i receive is: Failed to install mkdir /Users/[username]/.vim/pack/kite: permission denied.

**Comment by its-dhung** [comment]
Hi @BwL1289, does your user account have admin rights on the system?

**Comment by BwL1289** [comment]
Yup - i am the the only user (and superuser)

**Comment by edzkite** [comment]
Hi! Thanks for letting us know about the issue. As a quick sanity check, can you see if you can `mkdir` a test directory in your Home folder?

Also, if you go to Finder, right click on your Home directory, and select 'Get Info', what does the Sharing & Permissions section say?

**Comment by BwL1289** [comment]
See attached!

I have read/write permissions.

[image: Screen Shot 2019-05-02 at 10.44.33 AM.png]
--
Benjamin W. Leff
(516) 754-3453

**Comment by edzkite** [comment]
Thanks Benjamin! By any chance, does `~/.vim`, or any of its subdirectories we're trying to create, such as `~/.vim/pack/...` exist? If so, can you give the results of an `ls -l`?

(Also, for some reason I can't see the screenshot you attached via email on Github.com)

**Comment by BwL1289** [comment]
It looks like it does, here's a screenshot from the command line of both .vim and .vim/pack:

![Screen Shot 2019-05-05 at 2 57 07 PM](https://user-images.githubusercontent.com/17219379/57198871-13144480-6f46-11e9-9e0b-579379995582.png)


Also, screenshot from previous response:
![Screen Shot 2019-05-02 at 10 44 33 AM](https://user-images.githubusercontent.com/17219379/57198804-44404500-6f45-11e9-9985-c5beef380f80.png)


One other thing.... i guess i should open a separate request for this...but kit **_never_** seems to stop indexing for some reason in atom. Here's a screenshot:
![Screen Shot 2019-05-05 at 2 58 57 PM](https://user-images.githubusercontent.com/17219379/57198898-62f30b80-6f46-11e9-9df6-5af623fcf371.png)

![Screen Shot 2019-05-05 at 2 59 21 PM](https://user-images.githubusercontent.com/17219379/57198899-66869280-6f46-11e9-9a23-2815dadaf85c.png)


It wasn't always like this, but it has been this way for a number of weeks or more now.

**Comment by edzkite** [comment]
Thanks for letting us know Benjamin! I created an issue internally to track the Atom problem.

Re: Vim

1. Could you let me know what the permissions are for the `~/.vim/pack` folder?
2. Afterwards, could you remove the `~/.vim/pack` folder, then restart the Kite copilot app? If the Vim plugin doesn't install automatically, could you hit the Install button and see what happens?
3. Assuming the issue reoccurs, could you upload our client logs (located in `~/.kite/logs/client.log`?

Thanks again for bearing with us on this issue. Your help on this is much appreciated!

**Comment by its-dhung** [comment]
FYI @BwL1289, if it comes to it, you can also email your logs to feedback@kite.com instead of posting them publicly here.

**Comment by BwL1289** [comment]
@its-dhung thank you!

**Comment by BwL1289** [comment]
> Thanks for letting us know Benjamin! I created an issue internally to track the Atom problem.
> 
> Re: Vim
> 
> 1. Could you let me know what the permissions are for the `~/.vim/pack` folder?
> 2. Afterwards, could you remove the `~/.vim/pack` folder, then restart the Kite copilot app? If the Vim plugin doesn't install automatically, could you hit the Install button and see what happens?
> 3. Assuming the issue reoccurs, could you upload our client logs (located in `~/.kite/logs/client.log`?
> 
> Thanks again for bearing with us on this issue. Your help on this is much appreciated!

1. ![Screen Shot 2019-05-06 at 6 51 39 PM](https://user-images.githubusercontent.com/17219379/57260082-2ac7f780-7030-11e9-8cc7-1eb82ee9b8a6.png)

2. deleted the `pack` folder->restarted the app->didn't install automatically->installed manually->got the same error

3. emailing you the client logs now

**Comment by edzkite** [comment]
Hey Benjamin, 

I noticed that both the `.vim` and `.vim/pack` folders seem to be owned by `root` or `system` respectively. Could you try changing the permission of the `.vim` folder to be owned by you? Afterwards, delete the `pack` folder and try re-installing again. Let me know how it goes!

**Comment by BwL1289** [comment]
Boom! that worked. thank you! now i just have to get kite to stop indexing re: https://github.com/kiteco/plugins/issues/129#issuecomment-489453673

**Comment by edzkite** [comment]
Glad to hear! We have someone looking into it, will keep you posted when it's resolved.

**Comment by BwL1289** [comment]
Thanks!

**Comment by BwL1289** [comment]
> Glad to hear! We have someone looking into it, will keep you posted when it's resolved.

hey @edzkite, any update on this? (or a thread i can track?)

**Comment by its-dhung** [comment]
Hey @BwL1289, apologies for the delay here. Can you share path of the project you're working with that causes this behavior to happen?
