### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by novoid** [kiteco/plugins#13]
This is a placeholder issue that people interested in Kite are able to subscribe to until support for GNU/Linux is be ready.

Quote from https://kite.com/faq/

> For now, Kite only works on OS X, but we'll support Linux and Windows soon, too.

Thanks for your work!

**Comment by 4ni1** [comment]
I would like to contribute to this project, Linux support. Any advice is appreciated? A bug tracker?

**Comment by gauthamzz** [comment]
i would also like to contribute how can i help

**Comment by nickylimjj** [comment]
Interest in contributing here.

**Comment by HaleTom** [comment]
@novoid and Kite company,

The link above is 404.

It is worrying that 3 people have offered support with no reply.

Could you please clarify your business model, especially in relation to the open source community?

Is there any reason you've not been engaging?  Is it somehow detrimental to profits?  I'm cool with it if so, but just please be transparent about it.

**Comment by its-dhung** [comment]
Please refer to [our FAQ](https://help.kite.com/article/105-faq) for questions regarding our business model.
