### ISSUE TITLE
Kite engine cannot running in Intellij

### ISSUE THREAD

**Issue by wendingp** [kiteco/plugins#131]
IntelliJ latest version with Python Plugin installed:

> IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
...
For educational use only.
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Issue**: Kite status shows "Kite engine is not running" all the time, even after I click "Launch now" and Kite Copilot opens.

Kite works fine with Sublime Text on my Mac though.

**Comment by its-dhung** [comment]
Hi @wendingp, are you still able to get Kite's features working within PyCharm? Or does the Kite plugin not function at all?

**Comment by wendingp** [comment]
> Hi @wendingp, are you still able to get Kite's features working within PyCharm? Or does the Kite plugin not function at all?

Yeah I think it works, but I haven't used it for some time.

**Comment by its-dhung** [comment]
Thanks for the update! Going to close this issue then.
