### ISSUE TITLE
Kite stuck indexing

### ISSUE THREAD

**Issue by its-dhung** [kiteco/plugins#132]
Continuation of discussion #129 (cc @BwL1289)

**Comment by BwL1289** [comment]
it's happening to all projects, which are all located in /Users/benjaminleff/.atom. here are the permissions settings:
![Screen Shot 2019-05-21 at 3 54 41 PM](https://user-images.githubusercontent.com/17219379/58126357-cafd4f00-7be0-11e9-8fdc-06b3ac23db1b.png)

**Comment by its-dhung** [comment]
It seems like Kite's code indexer ignores files in `~/.atom`. I'll follow up with our engineering team to see why this is the case.

**Comment by BwL1289** [comment]
Thanks. It wasn’t always like this, but happened in the last few months.

**Comment by its-dhung** [comment]
Hi @BwL1289, Kite should be indexing `~/.atom` now. You can also [manually link the directory](https://help.kite.com/article/97-adding-libraries-from-pythonpath-to-the-kite-index) if necessary.
