### ISSUE TITLE
VIM: conflict with jedi (autocompletion)

### ISSUE THREAD

**Issue by Simarra** [kiteco/plugins#134]
# Config
- Ubuntu 18.04
- Neovim 4.0-888 (same problem in nvim 2.x and vim)

Hello, I don't know if this is a real issue but I have conflict when davidhalter/jedi is installed with automatic completion:
- Kite autocomplete force completion with the first letter typed and do not let me change completion.
![failing pic](https://media.giphy.com/media/IgXahM3JC6aJty7q3u/giphy.gif)

For now the workarround is to disable kit autocompletion:

```
let g:kite_auto_complete = 0
```

# Step to reproduce
- Install Plugin 'davidhalter/jedi-vim'
- Install Kite using the kite program
- start autocomplete in python3 file.

**Comment by airblade** [comment]
It doesn't really make sense to have two completions plugins because they will fight over the completions.

What behaviour would you expect/like to see happen here?

**Comment by HeRoq** [comment]
can we have both auto completion plugin one for python and other for angular ?

**Comment by its-dhung** [comment]
As @airblade mentioned, Kite's current Vim plugin will not work nicely with other completions plugins. However, Kite's plugin shouldn't be active for non Python files, so you should be able to use Kite for Python, and other plugins for other languages.
