### ISSUE TITLE
Confirm license

### ISSUE THREAD

**Issue by ariel11** [kiteco/plugins#136]
Can you please confirm if you intended for the License found at commit aedf7fa (https://github.com/kiteco/plugins/blob/aedf7fafe436873674bddd4b934ac289175bb5ef/LICENSE) to be the License for all the code in this repo?

**Comment by adamsmith** [comment]
Hi Ariel, we don't provide a license on all the code in this repo.

**Comment by ariel11** [comment]
@adamsmith Thanks.  Taking a closer look, this repo seems to primarily include screenshots.  I was trying to determine the license for Kite and the Kite plugins, as I do not see any license terms on the site (https://kite.com/).
