### ISSUE TITLE
Kite does not detect neovim on Linux

### ISSUE THREAD

**Issue by fonnesbeck** [kiteco/plugins#137]
Running the installer, I notice that it does not detect neovim on my system, even though it is my default editor. It finds vim and vscode and offers to install the plugin for those. Can it be installed manually?

Running version 2.20190627.0 on Debian

**Comment by metalogical** [comment]
Hi @fonnesbeck 

Sorry for the delay here.

As of the latest version of Kite, you should be able to get Kite to detect your editor by starting an `nvim` instance and then restarting the Kite engine while `nvim` is still running. Please try this and let us know if you are still having trouble. Then you can install the plugin, and restart `nvim` for changes to take effect.

You can also install manually: https://github.com/kiteco/vim-plugin, but installing through Kite has the benefit of Kite keeping your plugin up-to-date. We have a rolling release process, so old versions of the plugins are not guaranteed to always work with the latest version of Kite.

For now I'm going to close this issue. Feel free to reopen if the steps I described above don't work for you.
