### ISSUE TITLE
Keep the plugins in separate repositories?

### ISSUE THREAD

**Issue by davidawad** [kiteco/plugins#14]
This will make it easier to keep track of bugs across IDE's.

**Comment by kfatehi** [comment]
I agree, this would also be better for installation, for example once I get my invite I will want to use [vim-plug](https://github.com/junegunn/vim-plug) to install it via my .vimrc file.

**Comment by adamsmith** [comment]
Hi there, this is still a bit fragmented, but we watch this repo for new issues, and in some cases we have editor-specific plugin repos, e.g. https://github.com/kiteco/atom-plugin.  I know this is a bit confusing, but fortunately we watch the issues on all of these repos.  (Closing for now.)
