### ISSUE TITLE
Visual Studio Code Support

### ISSUE THREAD

**Issue by blackjid** [kiteco/plugins#15]

**Comment by akamud** [comment]
I'm interested in working on this but I need Kite first, how can contributors receive an invite?

**Comment by camerondubas** [comment]
+1 would also like to see VS Code support and would be willing to help contribute.

**Comment by emveeoh** [comment]
Any update on the status on Visual Studio Code support?

**Comment by testvinder** [comment]
Would love it too!

**Comment by adamsmith** [comment]
Hi there, Kite now has deep integration into VS Code.  Search for the "kite" plugin from the VS Code marketplace  : )
