### ISSUE TITLE
Kite does not work after laptop sleeps

### ISSUE THREAD

**Issue by pianocomposer321** [kiteco/plugins#153]
After putting my computer to sleep, when I open up Nvim, kite shows that it is ready in the statusline, but it does not complete any variable or method names. It works only after a restart (or if I shut it down instead of putting it to sleep).

**Comment by its-dhung** [comment]
Is this still an issue with the latest version of Kite?

**Comment by pianocomposer321** [comment]
IDK, I had actually been using Vscode for a while and am now trying to re-vamp my Neovim setup, and I haven't been experiencing the problem so far. I think it may have been a conflict with one of my other plugins at the time. Or maybe the latest version of kite fixed it. I really don't know.

**Comment by its-dhung** [comment]
Thanks for the update! Going to close this issue then.
