### ISSUE TITLE
Kite incompatible with Pycharm 2019.3?

### ISSUE THREAD

**Issue by Bben01** [kiteco/plugins#157]
When I launch Pycharm it notifies me with this: "Plugin Error: Plugin "Kite" is incompatible (target build range is 181.0 to 192.*)."
(Pycharm community)

**Comment by caelan-kite** [comment]
Hi there, Sorry for the inconvenience! We're working on this issue. 

However, Kite is presently compatible with PyCharm/IntelliJ 2019.3. Please use the Kite Copilot desktop app to uninstall and reinstall the Kite plugin for PyCharm. Then manually enable Kite via PyCharm plugin settings. This should complete the update. Restart PyCharm in the event you're still not seeing it work. 

We're also aware of a bug where Kite keeps on trying to update the PyCharm plugin after it has been updated. We'll post an update here once a fix is pushed for this bug, too.

**Comment by Bben01** [comment]
Ok, it worked great. Thank you for the fast response.

**Comment by yyily1314** [comment]
> Hi there, Sorry for the inconvenience! We're working on this issue.
> 
> However, Kite is presently compatible with PyCharm/IntelliJ 2019.3. Please use the Kite Copilot desktop app to uninstall and reinstall the Kite plugin for PyCharm. Then manually enable Kite via PyCharm plugin settings. This should complete the update. Restart PyCharm in the event you're still not seeing it work.
> 
> We're also aware of a bug where Kite keeps on trying to update the PyCharm plugin after it has been updated. We'll post an update here once a fix is pushed for this bug, too.

nice. I have tried and my problem is done!
