### ISSUE TITLE
How to install it in a virtual Machine.

### ISSUE THREAD

**Issue by aman5319** [kiteco/plugins#159]
I am using vim in a Amazon EC2 instance. How do i install it there?

**Comment by yochem** [comment]
Type this in the terminal:
`bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"` [source (make sure you select *linux*)](https://kite.com/download/#)

**Comment by its-dhung** [comment]
Closing this as the solution was mentioned by @yochem (thank you!).
