### ISSUE TITLE
Sublime Text 4 & Completions

### ISSUE THREAD

**Issue by jrappen** [kiteco/plugins#160]
Just a heads up, Sublime Text 4 is coming, currently in limited beta for users with a license. The completions engine is undergoing major changes.

See:

[![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord&style=flat-square)](https://discord.gg/D43Pecu)

See `#announcements` channel there for Changelog or download links to new builds. Full Changelog is available via the main menu **Sublime Text > Changelog** from within the app.

**Comment by its-dhung** [comment]
Hi @jrappen, thanks for letting us know! Where can we find full docs for changes to the API? The changelog doesn't seem to contain links to the new docs.

**Comment by jrappen** [comment]
They haven't been published, yet.

[Documentation for Sublime Text 3](https://www.sublimetext.com/docs/3/) is available on the site.

The changelog for the 4xxx Builds can be accessed as stated above.

**Comment by jrappen** [comment]
You can find all Sublime devs on that Discord and most (currently active) top plugin authors.

@its-dhung Will go ahead and close this for now.
