### ISSUE TITLE
Use fewer inotify_watches

### ISSUE THREAD

**Issue by its-dhung** [kiteco/plugins#167]
@metalogical, @jansorg: This is an issue to just publicly track progress. Please close it when the issue has been fixed.

**Comment by pgramme** [comment]
@its-dhung Thanks for having opened this issue in the beginning. Since you now closed it, does it mean it has been fixed? How can I avoid Kite taking an inotify_watch on every file under home dir?

**Comment by metalogical** [comment]
Yes, this has been fixed for quite some time, and the default behavior should not watch all files.

It will still watch every directories containing a Python file that has been indexed (which is the minimum necessary to ensure Kite's index stays up-to-date).

Just ensure you're on a relatively recent build of Kite.

**Comment by pgramme** [comment]
Awesome, thanks ! Will give it a try
