### ISSUE TITLE
Kite tries to open VS Code

### ISSUE THREAD

**Issue by its-dhung** [kiteco/plugins#171]
User reported this issue on Windows 10

> When I start my PC Kite also runs as startup process and after that 5 times it tries to open VS code.

**Comment by jansorg** [comment]
@its-dhung 
I couldn't reproduce this on Windows 10 with versions 1.41 and the current insiders build.

But we're running a few vscode commands at startup for detection and update. If the executables in place are different from what we're seeing, then this could happen, e.g. old or scripts of different installers.

I'd ask the user this:
- Which edition and version of VSCode is installed?
- The user could  run the commands below in a `cmd` window and see what's happening. The commands should print to the terminal, but not launch a vscode window.

We're detecting via start menu and common locations. These are the common paths commands we're using:
We're running these commands from the detected locations:

```
"c:\Program Files\Microsoft VS Code\bin\code" --list-extensions
"c:\Program Files\Microsoft VS Code\bin\code" --install-extension kiteco.kite --force

"%UserProfile%\AppData\Local\Programs\Microsoft VS Code\bin\code" --list-extensions
"%UserProfile%\AppData\Local\Programs\Microsoft VS Code\bin\code" --install-extension kiteco.kite
```
Insider program:
```
"c:\Program Files\Microsoft VS Code Insider\bin\code-insider" --list-extensions
"c:\Program Files\Microsoft VS Code Insider\bin\code-insider" --install-extension kiteco.kite --force

"%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-insiders" --list-extensions
"%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-insiders" --install-extension kiteco.kite
```

**Comment by its-dhung** [comment]
Closing this as we're unable to reproduce.

**Comment by jeremybramwell** [comment]
this seems to be an issue that many people are having.  see this vscode issue for steps to reproduce.
    
https://github.com/microsoft/vscode/issues/91613

It may require that you set vscode to run as an administrator" in the compatibility tab of the executables properties.    

This issue, of vscode opening the cli.js file periodically started happening to me today after I installed kite.

**Comment by 3038922** [comment]
me too.

**Comment by ucxorc** [comment]
me too.
Windows 10 1909
Python 3.8.3
VSCode 1.45.1

**Comment by metalogical** [comment]
Thanks all. We are currently investigating, and tracking the problem in #239. Leave any further feedback there.
