### ISSUE TITLE
PyCharm EAP 2020.1

### ISSUE THREAD

**Issue by fdellwing** [kiteco/plugins#172]
I'm using kite 1.4.6.193 and sadly it is not compatible with PyCharm EAP 2020.1 CE, which I need to use because the stable version is broken on my setup.

Any idea when kite will support this EAP version?

**Comment by jansorg** [comment]
@fdellwing 
support for the current EAPs will most likely be released later this week.

**Comment by fdellwing** [comment]
Am I correct, that with 2020.1 the plugin directory changed from `~/.PyCharmCE2019.3/plugins` to `~/.local/share/JetBrains/PyCharmCE2020.1`, or is this a fucked up situation of my installation?
