### ISSUE TITLE
Kite makes 2019.3 EAP not being able to write

### ISSUE THREAD

**Issue by boazdori** [kiteco/plugins#177]
I can't write to the editor when kite is installed!!

PyCharm 2019.3.3 (Professional Edition)
Build #PY-193.6494.30, built on February 6, 2020
Licensed to Boaz Dori
You have a perpetual fallback license for this version
Subscription is active until January 5, 2021
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 951M
Cores: 4
Registry: 
Non-Bundled Plugins: BashSupport, com.kite.intellij, com.markskelton.one-dark-theme
kite 1.2.27

**Comment by jansorg** [comment]
@boazdori This issue should have been resolved for a few weeks already. The current version is 1.4.x. 
It's probably to force an update like this:
- Close PyCharm
- Open Kite's Copilot
- Click that gear icon in the lower, right corner
- Open tab "Plugins"
- Click "Uninstall" for PyCharm and other JetBrains IDEs, then "Install" again

Please let us know how if this worked for you

**Comment by boazdori** [comment]
I uninstalled kite and reinstalled that sorted out the problem thanks
