### ISSUE TITLE
Can Kite coexist with YCM/Jedi?

### ISSUE THREAD

**Issue by AutoColin** [kiteco/plugins#179]
So I use vim on Ubuntu and it was convenient for me to use YCM plugin to edit C/Python files before, but what should i do if i wanna install Kite for Python autocomplete? Can they both exist? Or should I remove YCM or configure some features?

**Comment by metalogical** [comment]
They can co-exist, but Kite will automatically disable YCM when you open a `.py` buffer due to underlying incompatibilities.
