### ISSUE TITLE
[Pycharm] Kite doesn't  work when editing files in a remote server.

### ISSUE THREAD

**Issue by ZhouJf1202** [kiteco/plugins#183]
I tried to use Kite to help me edit files in a remote server,  but found it didn't work and the Kite icon at the   bottom right disappeared.
Kite works well when i edit a local file, so i think maybe it was because kite can't get access to a remote file? If so, how can i make kite to get the access?
Thanks in advance!
(It's my first time trying to submit an issue. 😂Please forgive me if there is anything inappropriate. Thanks again!)

**Comment by jansorg** [comment]
Hi @ZhouJf1202 , thank you for your report - it's good!
Can you tell how this remote file is opened in your IDE? e.g. via a file share, or a ssh connection, or somehow else?

**Comment by ZhouJf1202** [comment]
Thank you so much!😁 @jansorg 
I opened the remote file via a ssh connection by using Deployment in PyCharm. And I'm using a Mac, and the remote server runs Ubuntu.
Thank you again!

**Comment by jansorg** [comment]
Thanks. The IntelliJ plugin isn't supporting this yet. We'll take a look at this, but at this time I can't promise if/when this might be available.

**Comment by ZhouJf1202** [comment]
All right. I will wait for it with patience. Thank you!
