### ISSUE TITLE
Plugin manager looking in wrong directory for PyCharm 2020.1

### ISSUE THREAD

**Issue by its-dhung** [kiteco/plugins#185]
On macOS, PyCharm 2020.1 is installed in `$HOME/Library/Application Support/JetBrains/PyCharm2020.1`, but the plugin manager is looking in `$HOME/Library/Application Support/PyCharm2020.1`. The result is the user is unable to install the plugin.

**Comment by plungg** [comment]
Here is a list of installation paths that Sergey has compiled: https://kite.quip.com/Igi0AhSbIvIY/Editors-distributions-support-list#LAPACAohWqV

**Comment by jocelinqueau** [comment]
thanks for the fix 👍
