### ISSUE TITLE
IntelliJIdea2020.1

### ISSUE THREAD

**Issue by naah69** [kiteco/plugins#188]
idea of new version move plugin dir to `/Users/naah/Library/Application Support/JetBrains/IntelliJIdea2020.1`,instead of `/Users/naah/Library/Application Support/IntelliJIdea2020.1`
![image](https://user-images.githubusercontent.com/25682169/79444771-34165e00-800e-11ea-9a62-535588936a66.png)

![image](https://user-images.githubusercontent.com/25682169/79444643-07fadd00-800e-11ea-83a8-71b8b2e7af94.png)

**Comment by metalogical** [comment]
I think this should be fixed in the latest version of Kite. Please let us know if not.
