### ISSUE TITLE
Missing import highlight are not settled to the correct line number

### ISSUE THREAD

**Issue by Faylixe** [kiteco/plugins#28]
Received event for highlight event (type : "Missing import") are not set to the correct line number.

Example :

``` python
import requests

os.times()
```

Would trigger in **Kite** a suggestion for inserting `import os` at line #0, and the associated highlight event would point out the line #0, in the place where the import should be inserted. I think it would make more sense to highlight the component which requires the missing import (here line #3).

**Comment by adamsmith** [comment]
Hi @Faylixe we're now rebuilding this feature.  Thanks!
