### ISSUE TITLE
Incorrect Visual Studio Code Plugin installation instructions

### ISSUE THREAD

**Issue by DonJayamanne** [kiteco/plugins#42]
I believe the instructions won't work.
Downloading the vsix and opening it in VS Code doesn't work at my end.
I believe the extension needs to be published on the VS Code Market place.

@bnookala, pleas could you check this at your end?

**Comment by bnookala** [comment]
@DonJayamanne Looks like they changed it up the extension side loading a bit. I'll update the docs on my end, but I think what you need to do is use the `File -> Open` interface to open the .vsix file - dragging the extenstion file over the code editor to install it does not work.

**Comment by DonJayamanne** [comment]
@bnookala , I've got a Mac and when opening the vsix file from File->Open menu, nothing happens. I've tried this a coupe of times.
There's no feedback letting me know that it has worked

**Comment by bnookala** [comment]
@DonJayamanne can you try going to the extensions tab after you use the `File  -> Open` interface? It should appear there. You're right that there's no notification about a side-loaded plugin being installed, but I think that may be a bug on the VS Code side:

![kitecode](https://cloud.githubusercontent.com/assets/87996/17070071/dde13da8-500e-11e6-9693-005d049cfa28.gif)

**Comment by DonJayamanne** [comment]
Thanks @bnookala, will try that out.
However Wouldn't it be a better experience for the users if the extension was published into the market place?

**Comment by DonJayamanne** [comment]
Closed accidentally, also let's wait till docs have been updated

**Comment by bnookala** [comment]
@DonJayamanne Yes, that's the goal. But this is going to be published under Kite's name. As such, it's their responsibility to publish it themselves :)

**Comment by DonJayamanne** [comment]
If  that's the case I think we need to remove the notes on opening the extension via file-->Open.
Else I doubt it will ever get published.
I guess the main question is, is kite aware of the  fact that the extension needs to be published?

**Comment by bnookala** [comment]
@DonJayamanne yes, I've been working with them separately for that express purpose.
