### ISSUE TITLE
Where to download kite app????

### ISSUE THREAD

**Issue by Wushaowei001** [kiteco/plugins#49]

**Comment by jtbarker** [comment]
Would be great if this plugin were available in the pycharm plugins list.

**Comment by adamsmith** [comment]
Please sign up at kite.com for the time being.

**Comment by otymartin** [comment]
@adamsmith that sign-up is useless. No response for months unfortunately

**Comment by jtbarker** [comment]
I signed up and received my invitation yesterday.  Very excited to get started and thank you!

**Comment by otymartin** [comment]
@jtbarker lucky
