### ISSUE TITLE
PyCharm plugin does not detect PyCharm 2016.03 EAP installation

### ISSUE THREAD

**Issue by ericof** [kiteco/plugins#67]
Even though PyCharm is installed on the computer, Kite plugin does not detect it.

- OS: OSX 10.11.6
- PyCharm: PyCharm 2016.03 EAP
- PyCharm Location: /Applications/PyCharm.app

 Message: PyCharm is not installed on this machine

**Comment by mrfleap** [comment]
Same here but without the EAP and on Windows
- OS: Windows 10 Pro 1607
- PyCharm: PyCharm Professional 2017.1
- PyCharm Location: C:\Users\mrfleap\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\171.3780.115\bin

**Comment by mrfleap** [comment]
This may or may not be your problem, but I was able to fix it by installing it from the website. Kite doesn't recognize installation from the JetBrains Toolbox.

**Comment by pavanssetty** [comment]
Do you have plugin lib folder for PyCharm? It is not installing from Kite Settings. But able to detect PyCharm 2017.1 installation directory.
@mrfleap How did you get PyCharm plugin link from Kite website?

**Comment by mrfleap** [comment]
Sorry if I wasn't clear. I installed PyCharm originally via the Jetbrains Toolbox, but Kite didn't recognize this installation. I then reinstalled it from https://www.jetbrains.com/pycharm/download/ and it worked.

**Comment by pavanssetty** [comment]
I installed Kite first, then installed PyCharm from the link you shared about but guess I was not as lucky as you.
Opened up Kite Settings
![image](https://cloud.githubusercontent.com/assets/10538386/24665334/5c187a70-195d-11e7-8dd9-e600d954ebca.png)
Still not working.

**Comment by mrfleap** [comment]
Yeah my original problem was that Kite wasn't recognizing PyCharm, so not the same issue I guess. Do you get a popup in the bottom right from Kite when you start PyCharm?

**Comment by lostmsu** [comment]
Did not detect my IDEA 2017.1 Community Edition during installation either
OS: Win10 x64

**Comment by mrfleap** [comment]
@lostmsu Where's your IDEA's bin?
Should be something like %USERPROFILE%\.IntelliJIdeaXX.

**Comment by redxtech** [comment]
Anyone here who still needs it:

If your problem is Kite doesn't recognize your PyCharm installation because it was installed with Toolbox, go to the jetbrains website, download & install pycharm there, go to the kite settings browser page, install it for pycharm, and then delete the pycharm installation from the toolbox window, but remember to keep settings and plugins. The plugin is installed in %USERPROFILE%\.PyCharm2017.x\config\plugins\kite-pycharm\.

This is for windows only.

**Comment by adamsmith** [comment]
cc @calebperkins

**Comment by nextco** [comment]
Same problem here, Try to make this report as visual as possible to help.
OS: Windows 8.1 Pro x64

1. Main problem. Kite not detect PyCharm Community.
![1](https://cloud.githubusercontent.com/assets/4467154/24840931/288cf1e8-1d3d-11e7-9635-4525a51934cc.png)

2. What PyCharm versión?
![2](https://cloud.githubusercontent.com/assets/4467154/24840935/575a89c2-1d3d-11e7-812b-31f92eab3c69.png)

3. I tried install Jetbrains manually but not works.
![3](https://cloud.githubusercontent.com/assets/4467154/24840940/708e8bf0-1d3d-11e7-9e22-142a283ff82f.png)
![4](https://cloud.githubusercontent.com/assets/4467154/24840942/777039be-1d3d-11e7-942a-667bd9ae663a.png)

Extra info: 
- JetBrains PyCharm Community Path: A:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2

Atom works fine.

**Comment by adamsmith** [comment]
Hi everyone, we've made some fixes to our logic on Windows for detecting PyCharm installations in non-standard paths.  Could you visit http://localhost:46624/settings/plugins to see if your PyCharm installations are being detected now?

Thanks!

**Comment by adamsmith** [comment]
Closing for now, thanks!
