### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by jacquelineCelia** [kiteco/plugins#7]
@tarakju 
### Known issues
- [ ] Diff suggestions (highlight, apply) may not work if the relevant file isn't the file in focus.
- [ ] .py files with unicode characters (e.g. in string literals) won't work, in particular passive search for locations after such literals.
- [ ] Kite fails if UDP port 46625 isn't available for Kite to listen on. One common way this could happen: if multiple "Users" on the machine are running Kite.
- [ ] `error` actions should probably have their own json structure, since they don't include suggestions, and thus should put the error contents in a field instead of in `text` with an extra layer of json encoding.

**Comment by adamsmith** [comment]
Hi Jackie!  : )  Some of these are fixed, though the multiple-users one isn't yet.  Closing for now.
