### ISSUE TITLE
Keyboard shortcuts on non-qwerty keyboards

### ISSUE THREAD

**Issue by maxim-lian** [kiteco/plugins#71]
Is the `Apple-;` shortcut intended to focus on the Kite app?

When using a dvorak keyboard, this seems to override `Apple-s` (the same physical key as `Apple-;`), which is debilitating, for obvious reasons. 

Is there a way of disabling the shortcut / supporting non-qwerty keyboards?

**Comment by adamsmith** [comment]
Hi @maxim-lian, apologies for the delayed response here!

We've completely revamped the sidebar app, and moved it to Electron.  The Apple-; shortcut is now out of the app, so it shouldn't cause issues moving forward  : )
