### ISSUE TITLE
Your site claims Emacs support, but none is evident

### ISSUE THREAD

**Issue by aaron-em** [kiteco/plugins#8]
No plugin in this repo and none in MELPA, where "kite" is a package for integrating with the Webkit developer tools. But your site lists Emacs (as "emacs") among the supported editors. Until you find someone with the Emacs Lisp chops and the interest to build out the integration, you might want to remove Emacs from the supported editors list.

(I've got the chops, but not the interest, which is why this is an issue rather than a PR. I rarely use Python, and I'll almost certainly never want to use your product in any case - aside from which, I'm not real big on the idea of making a free contribution to what looks like it's going to grow up into a paid service offering. Sorry about that. It looks neat, though! Good luck with it.)

**Comment by cannyboy** [comment]
I came looking for Emacs support too. I'm guessing it it covered by the 'bring-your-own editor' mentioned in the video.

**Comment by aaron-em** [comment]
@cannyboy Well, all the other editors mentioned there are matched by plugins in this repository. Emacs isn't, so I presume a plugin needs to be either written or added to the repo.

**Comment by tarakju** [comment]
Hey guys. Tarak from Kite here. We're finalizing the emacs plugin. Should be available in the next week!

**Comment by ethanmick** [comment]
@tarakju Thanks, just came here from the site also, for Emacs. Looking forward to seeing it!

**Comment by eggcaker** [comment]
10 days ago

**Comment by JonnyWalker81** [comment]
Is it possible to get an update on the status of the Emacs plugin?

**Comment by kiipa** [comment]
Any updates on that plugin...?

**Comment by CestDiego** [comment]
I see you have an Emacs plugin folder, does this mean that the support is there now? @tarakju

**Comment by tarakju** [comment]
Yup! There is emacs support now, and Kite will install the emacs plugin for you during setup.

**Comment by CestDiego** [comment]
So how can I install it? I signed up for it but haven't got any emails. I would gladly help if there is anything to do with the Emacs plugin in my free time

**Comment by adamsmith** [comment]
Kite is now downloadable from kite.com  : )

**Comment by benley** [comment]
Looks like emacs support is gone again. Is it coming back eventually?
