### ISSUE TITLE
Clicking "def" doesn't lead to definition but goes to "untitled" instead

### ISSUE THREAD

**Issue by michalmonday** [kiteco/plugins#92]
All the functionality seems to work properly for me but the one mentioned in the title fails...
http://i.imgur.com/2mIeHrY.png

I included the python directory in the whitelisted directories but it didn't solve the problem.

**Comment by jansorg** [comment]
@michalmonday (cc @abe33 ) Thanks for your report!
The definition of the built-in requests module isn't available locally. The next update of the Atom plugin contains a workaround for this. A better fix for this is going to be in one of the next updates after that.

Did you expect it to open your local library file for requests? That might be the better approach here if you intuitively expected that behavior.

**Comment by adamsmith** [comment]
Closing for now.  I believe this is fixed, but please re-open if still an issue.  Thanks!
