### ISSUE TITLE
Pycharm custom key shortcut

### ISSUE THREAD

**Issue by Stekot** [kiteco/plugins#94]
Is it possible to set functionality currently asigned Ctrl+P and Ctrl+L in Settings -> Keymap. I am using keymap settings for Eclipse and default shortcuts doesn't work.

**Comment by jansorg** [comment]
Hi @Stekot,
that's possible. I just checked to make sure that it's working. The Eclipse keymap in PyCharm assigns Ctrl+Shift+Space to the menu item `View -> Quick Documentation` and no shortcut to `View -> Parameter info`. Check the View menu to see the assigned shortcuts.

You can assign your own shortcut by adjusting the default actions of PyCharm / IntelliJ. This screenshots shows the eclipse keymap for the Quick documentation feature:

![keymap-quick-doc](https://user-images.githubusercontent.com/11473063/29466948-03c1af5c-843f-11e7-9392-7aa558ed6788.png)

If this doesn't work with your setup please let us know. We'd need information about your IDE version and OS in that case.

**Comment by Stekot** [comment]
Thank you for your help, may I suggest adding this information to plugin documentation. I wasn't able to find it there.
