### ISSUE TITLE
Kite prevents SublimeText new file title behavior

### ISSUE THREAD

**Issue by astonm** [kiteco/plugins#95]
By default in ST, the first line of a new plain text file is used to set its tab's title (and its default filename when you choose to save it). However, with the Kite plugin installed, this behavior seems to be completely disabled.

I'm running Kite Version 0.20170914.0 and ST Version 3.0, Build 3143 (though I saw the same behavior on older builds of ST3 as well)

**Comment by adamsmith** [comment]
Hi @astonm!  It looks like this was fixed but please re-open if you're still seeing it.  Cheers!
