### ISSUE TITLE
Integration with Sublime 3

### ISSUE THREAD

**Issue by Wonay** [kiteco/plugins#96]
Hi ! 

on https://github.com/kiteco/plugins/tree/master/sublimetext3 the link is not working and the instruction are not really clear. I tried to install it using the `Package Control` but it doesnt seem to find it.

**Comment by adamsmith** [comment]
Hi @Wonay, thank you for the report!  Indeed those instructions were outdated.  I updated that README.md to point to kite.com which is currently the recommended way to get set up with Kite.

**Comment by Wonay** [comment]
okay thanks

**Comment by Wonay** [comment]
So there is no more integration with sublime ?

**Comment by adamsmith** [comment]
Kite supports Sublime Text 3.  You should see Kite detect your Sublime Text 3 installation during the setup flow, and it's one click to install the Kite plugin, along with the other software needed to use it (the native Kite app).

**Comment by Wonay** [comment]
Oh ok I see. Thanks
