### ISSUE TITLE
In plugins menu,it doesn't show sublime text

### ISSUE THREAD

**Issue by XuCcc** [kiteco/plugins#97]
![image](https://user-images.githubusercontent.com/18616776/31042095-fbb63872-a5d2-11e7-93a1-3cd0e2593c29.png)

My sublime text 3 version:

![image](https://user-images.githubusercontent.com/18616776/31042099-0b64e138-a5d3-11e7-9351-7e36e6f8fa73.png)

**Comment by jansorg** [comment]
Thanks for the report, @XuCcc !
Sublime should be detected. Could you paste the path where Sublime is installed?

**Comment by xiligey** [comment]
I have the same question as XuCcc.
And I installed sublime in "C:\Users\xiligey\Install\SublimeText3\sublime_text.exe"

**Comment by antonpolishko** [comment]
Same problem on Mac OS 10.14.2, with Sublime installed 
`/Applications/Sublime\ Text.app/`
which was installed using `brew cask install sublime-text`

**Comment by its-dhung** [comment]
Kite's plugin manager should now be able to detect Sublime Text as long as it's running.
