### ISSUE TITLE
Kite does not install on Sublime 3

### ISSUE THREAD

**Issue by mattjurek** [kiteco/plugins#99]
It will prompt me to install it, say its downloading in the background, never ever finishes. How do you even troubleshoot this?
  
More info: Sublime Text 3.0 Build 3143
Mac OS X: 10.11.6

**Comment by Haydnspass** [comment]
Neither does it in Atom, at least for both of my macs.
https://alpha.kite.com/release/dls/mac/current is not reachable as well, double checked that with http://downforeveryoneorjustme.com/https://alpha.kite.com/release/dls/mac/current.
I get the error
`dial tcp 52.9.240.18:5432: getsockopt: connection timed out`

**Comment by adamsmith** [comment]
Hi!  Apologies for the delayed response.

We had some server issues that should be resolved now!  Let us know if you're still having issues downloading Kite!  Thanks!

**Comment by mattjurek** [comment]
No this was never fixed. It will always prompt to install Kite and will continue to fail to install. This happens after you remove kite manually from the system.

**Comment by pierrehenrey** [comment]
For your information, if you use a VPN, that page might be blocked and unreachable. If you temporarily disable it, it should work.
